import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/providers/theme-provider';
import { cn } from '@/lib/utils';
import { ElectionFormProvider } from '@/providers/election-form-provider';
import { Toaster } from '@/components/ui/sonner';
import { AppProvider } from '@/providers/app-provider';

const dmSans = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(' min-h-screen', dmSans.className)} suppressHydrationWarning>
        <AppProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            disableTransitionOnChange
          >

            <ElectionFormProvider>
              <main>{children}</main>
              <Toaster position="top-right" richColors />
            </ElectionFormProvider>
          </ThemeProvider>
        </AppProvider>
      </body>
    </html>
  );
}
